remote_theme: IIP-Design/lab-notes

title: Style Templates Plugin
author: Bureau of Global Public Affairs (GPA) Digital Lab Team
author_homepage: https://github.com/IIP-Design
repository: IIP-Design/Style-Templates
description: WordPress plugin to add animated blocks to posts and pages.
favicon: /Style-Templates/assets/img/favicon.ico
logo: /Style-Templates/assets/img/dos_seal.svg
repo_name: 'Style-Templates'
show_downloads: true
show_nav: true

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
