remote_theme: IIP-Design/lab-notes
title: Style Templates Plugin
repository: IIP-Design/Style-Templates
description: WordPress plugin to add animated blocks to posts and pages.
favicon: /Style-Templates/assets/img/favicon.ico
logo: /Style-Templates/assets/img/dos_seal.svg
show_downloads: true
author: Bureau of Global Public Affairs (GPA) Digital Lab Team
author_homepage: https://github.com/IIP-Design
show_nav: true

highlighter: rouge
